---
- name: deploy  webserver
  hosts: webserver
  become: yes
  become_method: sudo
  vars:
     local_warfile: /var/lib/jenkins/workspace/HelloSimplLearn/target/HelloSimplLearn-0.0.1-SNAPSHOT.war
     remote_webapps: /opt/tomcat/webapps/
   
  tasks:
    - name: tomcat stop
      service: name=tomcat state=stopped

    - name: delete war directories in tomcat webapps
      file: path=/opt/tomcat/webapps/HelloSimplLearn-0.0.1-SNAPSHOT.war state=absent

    - name: delete war file in tomcat webapps
      file: path=/opt/tomcat/webapps/ state=absent
      
    - name: copying file with playbook
      become: true 
      copy:
        src: {{local_warfile}}
        dest: {{remote_webapps}}
        owner: devops
        group: devops        
        mode: 0644  
      notify: start tomcat


  handlers:
    - name: start tomcat
      service: name=tomcat state=started