- name: deploy  webserver
  hosts: webserver
  tasks:
   - debug: msg="Running Tomcat via Ansible"

   - name: Start tomcat
     become: yes
     become_user: devops
     shell: nohup /opt/tomcat/bin/startup.sh

  